{
 "title": "containerd容器监控大屏",
 "description": "cadvisor:v0.32.0",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "主机",
    "query": {
     "query": "label_values(kubernetes_io_hostname)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Container CPU Memory监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "运行的containerd数量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_processes{image!=\"\",kubernetes_io_hostname=~\"$server\"})"
    }
   ]
  },
  {
   "title": "Containerd使用内存总量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\",kubernetes_io_hostname=~\"$server\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Containerd使用CPU总量",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\",kubernetes_io_hostname=~\"$server\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "Container CPU使用情况",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{image!=\"\",kubernetes_io_hostname=~\"$server\",container!=\"\"}[5m]) * 100",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Container 内存使用情况",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{image!=\"\",kubernetes_io_hostname=~\"$server\",container!=\"\"}",
     "legendFormat": "{{container}}"
    }
   ]
  },
  { "title": "节点网卡出入流量监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Containerd容器入栈流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_receive_bytes_total{image!=\"registry.aliyuncs.com/google_containers/pause:3.6\",instance=~\"$server\"}[5m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  {
   "title": "Containerd容器出栈流量",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"registry.aliyuncs.com/google_containers/pause:3.6\",instance=~\"$server\"}[5m])",
     "legendFormat": "{{interface}}"
    }
   ]
  },
  { "title": "节点磁盘IO读取、写入监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Containerd容器-磁盘IO读取速率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{image!=\"\",container!=\"\",kubernetes_io_hostname=~\"$server\"}[5m])",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Containerd容器-磁盘IO写入速率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{image!=\"\",container!=\"\",kubernetes_io_hostname=~\"$server\"}[5m])",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}