{
 "title": "Kube-Apiserver状态和访问量监控",
 "description": "This is a modern API Server dashboard for your Kubernetes cluster(s). Made for kube-prometheus-stack and take advantage of the latest Grafana features. GitHub repository: https://github.com/dotdc/grafana-dashboards-kubernetes",
 "tags": [
  "Kubernetes",
  "Prometheus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "检查Kube-Apiserver状态",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"kubernetes-apiserver\"}",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "获取5分钟内访问Kube-Apiserver状态码总量",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(apiserver_request_total{code=\"200\"}) by (code) - sum(apiserver_request_total{code=\"200\"} offset 5m) by (code)",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum(apiserver_request_total{code=\"201\"}) by (code) - sum(apiserver_request_total{code=\"201\"} offset 5m) by (code)",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum(apiserver_request_total{code=\"404\"}) by (code) - sum(apiserver_request_total{code=\"404\"} offset 5m) by (code)",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum(apiserver_request_total{code=\"409\"}) by (code) - sum(apiserver_request_total{code=\"409\"} offset 5m) by (code)",
     "legendFormat": "{{code}}"
    },
    {
     "expr": "sum(apiserver_request_total{code=\"500\"}) by (code) - sum(apiserver_request_total{code=\"500\"} offset 5m) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "获取5分钟内访问Kube-Apiserver操作总量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(apiserver_request_total{verb=\"LIST\"}) by (verb) - sum(apiserver_request_total{verb=\"LIST\"} offset 5m) by (verb)",
     "legendFormat": "{{verb}}"
    },
    {
     "expr": "sum(apiserver_request_total{verb=\"DELETE\"}) by (verb) - sum(apiserver_request_total{verb=\"DELETE\"} offset 5m) by (verb)",
     "legendFormat": "{{verb}}"
    },
    {
     "expr": "sum(apiserver_request_total{verb=\"GET\"}) by (verb) - sum(apiserver_request_total{verb=\"GET\"} offset 5m) by (verb)",
     "legendFormat": "{{verb}}"
    },
    {
     "expr": "sum(apiserver_request_total{verb=\"WATCH\"}) by (verb) - sum(apiserver_request_total{verb=\"WATCH\"} offset 5m) by (verb)",
     "legendFormat": "{{verb}}"
    },
    {
     "expr": "sum(apiserver_request_total{verb=\"POST\"}) by (verb) - sum(apiserver_request_total{verb=\"POST\"} offset 5m) by (verb)",
     "legendFormat": "{{verb}}"
    },
    {
     "expr": "sum(apiserver_request_total{verb=\"PUT\"}) by (verb) - sum(apiserver_request_total{verb=\"PUT\"} offset 5m) by (verb)",
     "legendFormat": "{{verb}}"
    },
    {
     "expr": "sum(apiserver_request_total{verb=\"PATCH\"}) by (verb) - sum(apiserver_request_total{verb=\"PATCH\"} offset 5m) by (verb)",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "获取5分钟内访问Kube-Apiserver成功或失败总量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(authentication_attempts{result=\"success\"}) by (result) - sum(authentication_attempts{result=\"success\"} offset 5m) by (result)",
     "legendFormat": "{{result}}"
    },
    {
     "expr": "authentication_attempts{result=\"error\"}",
     "legendFormat": "{{result}}"
    }
   ]
  }
 ]
}